# Generated by Django 4.2.2 on 2023-06-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='book',
            name='poster',
            field=models.ImageField(upload_to='img/', verbose_name='poster'),
        ),
    ]
