# Generated by Django 4.2.3 on 2023-07-06 07:04

import books.fields
import books.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_rename_author_book_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=books.fields.WEBPField(default=datetime.datetime(2023, 7, 6, 7, 4, 2, 469091, tzinfo=datetime.timezone.utc), height_field='height', upload_to=books.models.image_folder, verbose_name='Image', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='width',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Width'),
        ),
    ]
