# Generated by Django 4.2.2 on 2023-06-30 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='picture',
        ),
    ]
